### ISSUE TITLE
一个很奇怪又很致命的bug

### ISSUE THREAD

**Issue by yunboom** [huaweicloud/huaweicloud-sdk-go-obs#9]
![image](https://user-images.githubusercontent.com/56998421/130018820-2b60a32f-4c0d-412c-a121-e8d079c215ff.png)

因为判断err再defer close之后执行导致该bug、但是正常来说这行代码应该会panic空指针、然而事实是该请求的线程被无限阻塞、并且控制台没有打印panic信息

**Comment by x00403408** [comment]
你好，已经收到你的反馈，从语法上来看如果这里output.Body为空就会触发panic；从你当前提供的信息没有办法确认你的程序是否走到了73行，需要你进一步单步调试来判断程序执行到了哪个语句；SDK本身没有阻塞的业务逻辑，从当前信息来看怀疑你的程序由于网络原因阻塞在网络请求过程中，由于未达到网络超时时间所以出现了一段时间没有返回output和err的正常现象；
![image](https://user-images.githubusercontent.com/44666668/130188340-1adfd77d-06bc-4cf4-8193-f6e63f61e4fe.png)

**Comment by x00403408** [comment]
您好，由于一个月内没有收到您的进一步反馈，我们会关闭该issue，如果您后续有其他问题，可以在新的issue中反馈，谢谢；
